export const data = [
  {
    id: '1',
    user_id: `5`,
    createDt: '2021-08-22 08:18:49',
    reply: 'greattttt',
    userImg: 'https://imagePath.com/changed',
    usreNick: 'grimes',
  },
  {
    id: '2',
    user_id: `5`,
    createDt: '2021-08-22 08:18:49',
    reply: 'magnifique!',
    userImg: 'https://imagePath.com/changed',
    usreNick: 'lapiere',
  },
  {
    id: '3',
    user_id: `5`,
    createDt: '2021-08-22 08:18:49',
    reply: '와 대단!',
    userImg: 'https://imagePath.com/changed',
    usreNick: '영수',
  },
  {
    id: '4',
    user_id: `5`,
    createDt: '2021-08-22 08:18:49',
    reply: 'I would said that happy!',
    userImg: 'https://imagePath.com/changed',
    usreNick: 'sara',
  },
  {
    id: '5',
    user_id: `5`,
    createDt: '2021-08-22 08:18:49',
    reply: '!!!!!!!!!!!!!!!',
    userImg: 'https://imagePath.com/changed',
    usreNick: '!!!',
  },
  {
    id: '6',
    user_id: `5`,
    createDt: '2021-08-22 08:18:49',
    reply: 'skjdasd!',
    userImg: 'https://imagePath.com/changed',
    usreNick: 'fsfsf',
  },
];
